### ISSUE TITLE
cnpm run dev 报错了

### ISSUE THREAD

**Issue by Acerkaio** [Tomotoes/HomePage#5]
## 版本信息如下
```
cnpm@9.2.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@9.8.1 (/usr/local/lib/node_modules/cnpm/node_modules/npm/index.js)
node@20.6.0 (/usr/local/bin/node)
```

## 报错信息如下

```
> tomotoes-home-page@1.0.0 predev
> gulp build

[20:51:41] Using gulpfile /home/acerkaio/桌面/HomePage/gulpfile.js
[20:51:41] Starting 'build'...
[20:51:41] Starting 'clean'...
[20:51:41] Finished 'clean' after 3.62 ms
[20:51:41] Starting 'assets'...
[20:51:41] Finished 'assets' after 21 ms
[20:51:41] Starting 'pug'...
[20:51:41] Finished 'pug' after 106 ms
[20:51:41] Starting 'css'...
Error in plugin "gulp-sass"
Message:
    
gulp-sass no longer has a default Sass compiler; please set one yourself.
Both the "sass" and "node-sass" packages are permitted.
For example, in your gulpfile:

  const sass = require('gulp-sass')(require('sass'));

[20:51:41] The following tasks did not complete: build, css
[20:51:41] Did you forget to signal async completion?

```

**Comment by HeDaoTONGZHI** [comment]
> tomotoes-home-page@1.0.0 predev
> gulp build

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (115)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\Linyu\Desktop\Blog\HomePage\node_modules\.store\node-sass@4.14.1\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\Linyu\Desktop\Blog\HomePage\node_modules\.store\node-sass@4.14.1\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\Linyu\Desktop\Blog\HomePage\node_modules\.store\gulp-sass@4.1.1\node_modules\gulp-sass\index.js:166:21)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
我是这个

**Comment by justeHe** [comment]
> ## 版本信息如下
> ```
> cnpm@9.2.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
> npm@9.8.1 (/usr/local/lib/node_modules/cnpm/node_modules/npm/index.js)
> node@20.6.0 (/usr/local/bin/node)
> ```
> 
> ## 报错信息如下
> ```
> > tomotoes-home-page@1.0.0 predev
> > gulp build
> 
> [20:51:41] Using gulpfile /home/acerkaio/桌面/HomePage/gulpfile.js
> [20:51:41] Starting 'build'...
> [20:51:41] Starting 'clean'...
> [20:51:41] Finished 'clean' after 3.62 ms
> [20:51:41] Starting 'assets'...
> [20:51:41] Finished 'assets' after 21 ms
> [20:51:41] Starting 'pug'...
> [20:51:41] Finished 'pug' after 106 ms
> [20:51:41] Starting 'css'...
> Error in plugin "gulp-sass"
> Message:
>     
> gulp-sass no longer has a default Sass compiler; please set one yourself.
> Both the "sass" and "node-sass" packages are permitted.
> For example, in your gulpfile:
> 
>   const sass = require('gulp-sass')(require('sass'));
> 
> [20:51:41] The following tasks did not complete: build, css
> [20:51:41] Did you forget to signal async completion?
> ```

在文件gulpfile.js 中, 将第12行替换为const sass = require('gulp-sass')(require('sass'))
然后注释掉第13行sass.compiler = require('node-sass')就可以跑了

**Comment by SimonAKing** [comment]
已去掉 sass
